apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: python
        command: ["python3", "-c", "import time; print('START'); time.sleep(20); print('OK')"]
      restartPolicy: Never
  backoffLimit: 4